package bai08;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author blackd000
 */
public class Bai08 extends javax.swing.JFrame {

	String fileName = "employee.txt";
	Vector<String> header = new Vector<String>();
	Vector data = new Vector();
	boolean addNew = false;
	boolean changed = false;

	/**
	 * Creates new form Bai08
	 */
	public Bai08() {
		initComponents();
		this.setSize(590, 365);
		this.setLocationRelativeTo(null);

		header.add("Code");
		header.add("Name");
		header.add("Salary");
		loadData();
		DefaultTableModel tblModel;
		tblModel = (DefaultTableModel) this.tblEmp.getModel();
		tblModel.setDataVector(data, header);
	}

	private void loadData() {
		try {
			File f = new File(fileName);
			FileReader fr = new FileReader(f);
			BufferedReader br = new BufferedReader(fr);

			String aDetails;
			while ((aDetails = br.readLine()) != null) {
				StringTokenizer stk = new StringTokenizer(aDetails, ",");
				String code = stk.nextToken();
				String name = stk.nextToken();
				String salaryStr = stk.nextToken();
				Vector<String> v = new Vector<String>();
				v.add(code);
				v.add(name);
				v.add(salaryStr);
				data.add(v);
			}
			br.close();
			fr.close();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "The file " + fileName + "not found.");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbCode = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbSalary = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        lbHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Manager");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        tblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblEmpMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 290, 230);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew);
        btnNew.setBounds(10, 290, 72, 23);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(120, 290, 73, 23);

        btnSaveToFile.setText("Save to file");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveToFile);
        btnSaveToFile.setBounds(240, 290, 100, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(380, 290, 72, 23);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(490, 290, 72, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(null);

        lbCode.setText("Code:");
        jPanel1.add(lbCode);
        lbCode.setBounds(30, 40, 40, 16);

        lbName.setText("Name:");
        jPanel1.add(lbName);
        lbName.setBounds(30, 100, 40, 16);

        lbSalary.setText("Salary:");
        jPanel1.add(lbSalary);
        lbSalary.setBounds(30, 160, 40, 16);
        jPanel1.add(txtCode);
        txtCode.setBounds(90, 40, 71, 22);
        jPanel1.add(txtName);
        txtName.setBounds(90, 100, 130, 22);
        jPanel1.add(txtSalary);
        txtSalary.setBounds(90, 160, 71, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 40, 260, 230);

        lbHeader.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbHeader.setText("Employee List");
        getContentPane().add(lbHeader);
        lbHeader.setBounds(10, 0, 200, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
		if (changed == true) {
			if (JOptionPane.showConfirmDialog(this, "Data changed. Save Y/N?") == JOptionPane.OK_OPTION) {
				btnSaveActionPerformed(null);
			}
		}
		System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
		String code = txtCode.getText();
		String name = txtName.getText();
		String salaryStr = txtSalary.getText();
		if (addNew) {
			Vector v = new Vector();
			v.add(code);
			v.add(name);
			v.add(salaryStr);
			data.add(v);
			addNew = false;
		} else {
			int pos = tblEmp.getSelectedRow();
			Vector v = (Vector) data.get(pos);
			v.set(1, name);
			v.set(2, salaryStr);
		}
		tblEmp.updateUI();
		changed = true;
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
		this.addNew = true;
		this.txtCode.setText("");
		this.txtCode.setEditable(true);
		this.txtName.setText("");
		this.txtSalary.setText("");
		this.txtCode.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
		// TODO add your handling code here:
		try {
			File f = new File(fileName);
			PrintWriter pw = new PrintWriter(f);
			int n = tblEmp.getRowCount();
			for (int i = 0; i < n; i++) {
				Vector<String> v = (Vector<String>) (data.get(i));
				String s = v.get(0) + "," + v.get(1) + "," + v.get(2);
				pw.println(s);
			}
			pw.close();
			changed = false;

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e);
		}
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
		// TODO add your handling code here:
		int pos = this.tblEmp.getSelectedRow();
		if (pos >= 0) {
			String code = (String) (tblEmp.getValueAt(pos, 0));
			if (JOptionPane.showConfirmDialog(this, "Delete the " + code + " employee ?") == JOptionPane.OK_OPTION) {
				data.remove(pos);
				tblEmp.updateUI();
				changed = true;
			}
		}
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
		// TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
		// TODO add your handling code here:
		int row = this.tblEmp.getSelectedRow();
		this.txtCode.setText((String) (tblEmp.getValueAt(row, 0)));
		this.txtCode.setEditable(false);
		this.txtName.setText((String) (tblEmp.getValueAt(row, 1)));
		this.txtSalary.setText((String) (tblEmp.getValueAt(row, 2)));
		addNew = false;
    }//GEN-LAST:event_tblEmpMouseClicked

    private void tblEmpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseReleased
		// TODO add your handling code here:
		if (this.tblEmp.isEditing()) {
			int row = tblEmp.getSelectedRow();
			int column = tblEmp.getSelectedColumn();
			tblEmp.getCellEditor(row, column).cancelCellEditing();
		}
    }//GEN-LAST:event_tblEmpMouseReleased

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Bai08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Bai08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Bai08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Bai08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bai08().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSalary;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
