/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cau2;

import javax.swing.JOptionPane;

/**
 *
 * @author blackd000
 */
public class PhieuTinhTienNuoc extends javax.swing.JFrame {

	/**
	 * Creates new form PhieuTinhTienNuoc
	 */
	public PhieuTinhTienNuoc() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRight = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JTextField();
        lblBottom = new javax.swing.JPanel();
        btnTinh = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThongTin = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lblMain = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtChiSoCu = new javax.swing.JTextField();
        txtChiSoMoi = new javax.swing.JTextField();
        txtTieuThu = new javax.swing.JTextField();
        txtPhiMoiTruong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Phiếu Tính Tiền Nước");
        lblTop.add(jLabel1);

        getContentPane().add(lblTop, java.awt.BorderLayout.PAGE_START);

        lblRight.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Giá bán");
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 18));
        lblRight.add(jLabel2);
        lblRight.add(txtGiaBan);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VTA");
        jLabel3.setPreferredSize(new java.awt.Dimension(130, 18));
        lblRight.add(jLabel3);
        lblRight.add(txtVTA);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tổng cộng");
        jLabel4.setPreferredSize(new java.awt.Dimension(130, 18));
        lblRight.add(jLabel4);
        lblRight.add(txtTongCong);

        getContentPane().add(lblRight, java.awt.BorderLayout.LINE_END);

        lblBottom.setBackground(new java.awt.Color(204, 204, 204));
        lblBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        lblBottom.add(btnTinh);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        lblBottom.add(btnXoa);

        btnThongTin.setText("Thông tin");
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });
        lblBottom.add(btnThongTin);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        lblBottom.add(btnThoat);

        getContentPane().add(lblBottom, java.awt.BorderLayout.PAGE_END);

        jLabel5.setText("Chỉ số cũ");

        jLabel6.setText("Chỉ số mới");

        jLabel7.setText("Tiêu thụ");

        jLabel8.setText("Phí môi trường");

        javax.swing.GroupLayout lblMainLayout = new javax.swing.GroupLayout(lblMain);
        lblMain.setLayout(lblMainLayout);
        lblMainLayout.setHorizontalGroup(
            lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMainLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChiSoMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChiSoCu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTieuThu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhiMoiTruong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        lblMainLayout.setVerticalGroup(
            lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMainLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtChiSoCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtChiSoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTieuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPhiMoiTruong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(lblMain, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
		int chiSoCu = 0, chiSoMoi = 0;
		do {
			chiSoCu = Integer.parseInt(txtChiSoCu.getText());
			chiSoMoi = Integer.parseInt(txtChiSoMoi.getText());
			if (chiSoCu > chiSoMoi) {
				JOptionPane.showConfirmDialog(this, 
					"chi so cu phai be hon", "loi", JOptionPane.ERROR_MESSAGE);
				txtChiSoCu.setText("");
				txtChiSoMoi.setText("");
			}
		} while (chiSoCu > chiSoMoi);

		int tieuThu = chiSoMoi - chiSoCu;

		int gia = 0;
		if (tieuThu >= 1 && tieuThu <= 12) {
			gia = 6500;
		} else if (tieuThu >= 13) {
			gia = 11500;
		}

		double giaBan = tieuThu * gia;
		double vta = giaBan * 0.1;
		double phiMoiTruong = Double.parseDouble(txtPhiMoiTruong.getText());
		double tongCong = giaBan + vta + phiMoiTruong;

		txtTieuThu.setText(tieuThu + "");
		txtGiaBan.setText(giaBan + "");
		txtVTA.setText(vta + "");
		txtTongCong.setText(tongCong + "");
    }//GEN-LAST:event_btnTinhActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
		txtChiSoCu.setText("");
		txtChiSoMoi.setText("");
		txtTieuThu.setText("");
		txtPhiMoiTruong.setText("");
		txtGiaBan.setText("");
		txtVTA.setText("");
		txtTongCong.setText("");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
		JOptionPane.showConfirmDialog(this, "CT0N0112 - Cay Trieu Dong - CT6N");
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
		int xn = JOptionPane.showConfirmDialog(this, "Chac chua", "Thoat", 
			JOptionPane.YES_NO_OPTION);
		if (xn == JOptionPane.YES_OPTION) {
			this.dispose();
		}
    }//GEN-LAST:event_btnThoatActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PhieuTinhTienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PhieuTinhTienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PhieuTinhTienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PhieuTinhTienNuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PhieuTinhTienNuoc().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnTinh;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel lblBottom;
    private javax.swing.JPanel lblMain;
    private javax.swing.JPanel lblRight;
    private javax.swing.JPanel lblTop;
    private javax.swing.JTextField txtChiSoCu;
    private javax.swing.JTextField txtChiSoMoi;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtPhiMoiTruong;
    private javax.swing.JTextField txtTieuThu;
    private javax.swing.JTextField txtTongCong;
    private javax.swing.JTextField txtVTA;
    // End of variables declaration//GEN-END:variables
}
